### ISSUE TITLE
OSError: Couldn't open webcam or video

### ISSUE THREAD

**Issue by Angel0003** [GlassyWing/yolo_deepsort#1]
使用 python video_deepsort.py  VIDEO_PATH为什么还是提示上面的错误？代码里还需要改什么吗

**Comment by GlassyWing** [comment]
拉取最新的代码试试，另外检测一下视频文件的路径是否正确

**Comment by Angel0003** [comment]
> 拉取最新的代码试试，另外检测一下视频文件的路径是否正确
重新下的代码，然后 python video_deepsort.py VIDEO_PATH，还是同样的错误呢，视频路径没错的

**Comment by GlassyWing** [comment]
没有设置接收命令行参数，你需要在video_deepsort.py 47行手动更改视频路径：
```
    for image, detections, _ in video_detector.detect("E:/python/data/toky.flv",
                                                      # output_path="data/output.mp4",
                                                      real_show=True,
                                                      skip_secs=0 * 60):
        pass
```

**Comment by Angel0003** [comment]
for image, detections, _ in video_detector.detect( "./person.mp4",
                                                      real_show=True,
                                                      skip_secs=0*60):
        pass

是的，我改了的,不支持MP4格式吗

**Comment by Angel0003** [comment]
for image, detections, _ in video_detector.detect( "person.mp4",
                                                      real_show=True,
                                                      skip_secs):
        pass

我改了的，是不支持MP4格式吗

**Comment by GlassyWing** [comment]
嗯。。。MP4分为很多种，不过一般的都支持，换成绝对路径试试

**Comment by Angel0003** [comment]
> 嗯。。。MP4分为很多种，不过一般的都支持，换成绝对路径试试
很贊！速度比yolo3快多了，要是有一些準確率定性評估就完美了哈哈

IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP IDt IDa IDm
MOT16-02 24.9% 54.0% 16.2% 25.2% 83.7% 54 5 19 30 873 13348 70 190 19.9% 0.316 75 13 19
MOT16-04 40.3% 65.2% 29.1% 37.8% 84.6% 83 6 42 35 3279 29586 124 600 30.6% 0.292 100 30 16
MOT16-05 35.4% 44.9% 29.3% 54.8% 84.0% 125 27 65 33 712 3079 64 155 43.5% 0.300 138 5 82
MOT16-09 40.6% 51.6% 33.4% 58.5% 90.6% 25 6 17 2 321 2180 59 94 51.3% 0.271 59 4 10
MOT16-10 32.0% 46.2% 24.5% 41.9% 79.0% 54 9 21 24 1376 7151 132 321 29.7% 0.304 132 15 32
MOT16-11 36.7% 46.6% 30.3% 57.6% 88.7% 69 13 23 33 672 3888 35 87 49.9% 0.257 55 5 26
MOT16-13 23.5% 42.5% 16.3% 25.5% 66.5% 107 6 40 61 1472 8530 131 379 11.5% 0.352 146 22 47
OVERALL 34.8% 54.8% 25.5% 38.6% 83.0% 517 72 227 218 8705 67762 615 1826 30.2% 0.295 705 
樓主知道這些多目標跟蹤的評價指標怎麼跑出來嗎，你這裏有實現嗎

**Comment by GlassyWing** [comment]
这个仓库只是优化了代码，提升预测速度，采用的依然是官方的yolo权重文件，没有包含评价程序。你如果在video_deepsort中换成yolov3的权重和配置文件，速度会更快。默认是yolov4的，yolov4推理速度更慢，但准确度更高。

**Comment by Angel0003** [comment]
> 这个仓库只是优化了代码，提升预测速度，采用的依然是官方的yolo权重文件，没有包含评价程序。你如果在video_deepsort中换成yolov3的权重和配置文件，速度会更快。默认是yolov4的，yolov4推理速度更慢，但准确度更高。

我把模型換成yolo3的速度變慢啦。準確性因爲沒有準確率看不太出來，視頻效果看着差不多。

**Comment by GlassyWing** [comment]
真是奇怪，在我的电脑上yolo3要快一些。最新的提交在检测框上加上了精度显示（只在不适用tracker时生效），你可以进行拉取测试。

**Comment by Angel0003** [comment]
> 真是奇怪，在我的电脑上yolo3要快一些。最新的提交在检测框上加上了精度显示（只在不适用tracker时生效），你可以进行拉取测试。
  你的fps計算方式我咋沒看懂，不是一幀圖像輸出一次嗎，可以加V交流嗎大佬18811012778

**Comment by GlassyWing** [comment]
FPS 计算的是平均FPS, 即在1s内处理的图像数量，所以是每秒更新
