### ISSUE TITLE
请问一下如果选择其他的目标呢，比如我想框住车辆，该如何更改或者训练呢

### ISSUE THREAD

**Issue by zzc-ai** [GlassyWing/yolo_deepsort#13]
OSError: Couldn't open webcam or video

**Comment by GlassyWing** [comment]
1.在class_mask参数中添加你要跟踪目标的分类ID;
【2-3】步是可选的，为了增强跟踪器性能可以选择训练DeepSort：
2.在车辆数据集上重新训练reid模型，使用该仓库代码进行训练:https://github.com/ZQPei/deep_sort_pytorch
3.将训练得到的ckpt.t7替换原来的ckpt.t7即可

**Comment by zzc-ai** [comment]
太感谢了，我会尝试一下的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GlassyWing/yolo_deepsort"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 上午9:03
收件人:&nbsp;"GlassyWing/yolo_deepsort"<yolo_deepsort@noreply.github.com&gt;;
抄送:&nbsp;"自动化学生张子诚"<853193368@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GlassyWing/yolo_deepsort] 请问一下如果选择其他的目标呢，比如我想框住车辆，该如何更改或者训练呢 (#13)





 
1.在class_mask参数中添加你要跟踪目标的分类ID;
 【2-3】步是可选的，为了增强跟踪器性能可以选择训练DeepSort：
 2.在车辆数据集上重新训练reid模型，使用该仓库代码进行训练https://github.com/ZQPei/deep_sort_pytorch，训练方法参考该库
 3.将训练得到的ckpt.t7替换原来的ckpt.t7即可
