### ISSUE TITLE
显示

### ISSUE THREAD

**Issue by yishunzhijian** [GlassyWing/yolo_deepsort#14]
请问实时显示的视频中类别和编号都不清晰，有改进的空间吗？

**Comment by GlassyWing** [comment]
如果你安装了编译了feetype组件的opencv，那么你可以直接在VideoDetector中设置font_path 和font_size。
默认使用的是opencv提供的原生字体支持，原生字体一般渲染都不怎么样，会因图像大小变化造成模糊
当然如果没有安装freetype的opencv,那就只能在这里对putText函数进行调试
https://github.com/GlassyWing/yolo_deepsort/blob/3e7a6e4f224df0eff8ada85d63622b1a0caa7d3e/yolo3/utils/label_draw.py#L57
你可以对font_type, font_size, thinkness 进行调试，详情请参阅opencv putText api

**Comment by yishunzhijian** [comment]
请问你的opencv版本是多少？我的是opencv 3.4.3  ，出现AttributeError: module 'cv2.cv2' has no attribute 'freetype'的错误

**Comment by GlassyWing** [comment]
> 请问你的opencv版本是多少？我的是opencv 3.4.3 ，出现AttributeError: module 'cv2.cv2' has no attribute 'freetype'的错误

feetype 不在opencv中原生支持，你需要添加第三方模块https://github.com/opencv/opencv_contrib，然后重新编译opencv才行，

**Comment by yishunzhijian** [comment]
谢谢，通过修改cv2.putText效果就可以了
