### ISSUE TITLE
How to save the output video? 

### ISSUE THREAD

**Issue by err-or** [GlassyWing/yolo_deepsort#16]
Hi! I am running the repo on google colab. I have successfully able to use the code and run the tracking on my video but the output video is not saving even though I have specified the path. 
![image](https://user-images.githubusercontent.com/61436133/89842580-0a94bb80-db44-11ea-93de-15dfa1f11b62.png)

According to the path, the output video is supposed to be stored at "data/" but after finishing the tracking the does not get saved. Can you please tell me how can I save the output prediction?

Thank you!

**Comment by GlassyWing** [comment]
Please make sure the path is correct, this path is the parent directory of the current directory.

**Comment by err-or** [comment]
Hi thank you for your response. It was my mistake, the path was wrong. Thank you for your great work!
