### ISSUE TITLE
frames的值爲什麼只有1和2，怎麼正常顯示幀數？

### ISSUE THREAD

**Issue by Angel0003** [GlassyWing/yolo_deepsort#3]
if frames % self.skip_frames == 0:這麼處理的作用是什麼？skip_frames作用是什麼？
frames的值只有1和2，怎麼正常顯示幀數，並且能來一幀圖像處理一幀？

**Comment by GlassyWing** [comment]
skip_frames指的是跳帧处理，比如2表示每2帧检测一次，如果想每帧处理，设置为1即可，这样就不会跳帧

**Comment by Angel0003** [comment]
> skip_frames指的是跳帧处理，比如2表示每2帧检测一次，如果想每帧处理，设置为1即可，这样就不会跳帧

2,1,690.5098,604.3442,48.11621,66.473816,0.9873046875,2,-1,-1
2,2,624.21564,652.5629,55.833313,94.67615,0.98388671875,2,-1,-1
2,3,543.73895,520.6535,42.325928,60.114014,0.951171875,2,-1,-1
2,5,577.2914,470.5832,38.793823,39.09305,0.591796875,2,-1,-1
2,6,695.8915,525.0203,35.712708,47.11963,0.9453125,2,-1,-1
2,7,699.44855,431.1463,24.614685,25.808441,0.8173828125,2,-1,-1
2,9,748.4025,428.03967,26.481812,26.176147,0.9013671875,2,-1,-1
2,10,746.7273,530.39136,32.677917,38.32538,0.9140625,2,-1,-1
2,11,746.6097,405.83228,16.919495,18.731812,0.58984375,2,-1,-1
2,1,689.91064,610.44495,49.17206,68.15271,0.99072265625,2,-1,-1
2,2,623.7692,664.89124,54.416504,92.378784,0.9794921875,2,-1,-1
2,3,539.9749,528.04517,43.02179,60.783875,0.978515625,2,-1,-1
2,5,576.8351,474.88745,39.076233,39.35431,0.87060546875,2,-1,-1
2,6,695.9689,528.6532,36.289673,48.0719,0.96875,2,-1,-1
2,7,700.5949,432.3939,25.233582,26.458405,0.79736328125,2,-1,-1
2,9,749.7373,429.80667,27.284729,27.143951,0.88671875,2,-1,-1
1,1,690.5098,604.3442,48.11621,66.473816,0.9873046875,2,-1,-1
1,2,624.21564,652.5629,55.833313,94.67615,0.98388671875,2,-1,-1
1,3,543.73895,520.6535,42.325928,60.114014,0.951171875,2,-1,-1
1,5,577.2914,470.5832,38.793823,39.09305,0.591796875,2,-1,-1
1,6,695.8915,525.0203,35.712708,47.11963,0.9453125,2,-1,-1
1,7,699.44855,431.1463,24.614685,25.808441,0.8173828125,2,-1,-1
1,9,748.4025,428.03967,26.481812,26.176147,0.9013671875,2,-1,-1
1,10,746.7273,530.39136,32.677917,38.32538,0.9140625,2,-1,-1
1,11,746.6097,405.83228,16.919495,18.731812,0.58984375,2,-1,-1
1,1,689.91064,610.44495,49.17206,68.15271,0.99072265625,2,-1,-1
1,2,623.7692,664.89124,54.416504,92.378784,0.9794921875,2,-1,-1
1,3,539.9749,528.04517,43.02179,60.783875,0.978515625,2,-1,-1
1,5,576.8351,474.88745,39.076233,39.35431,0.87060546875,2,-1,-1
1,6,695.9689,528.6532,36.289673,48.0719,0.96875,2,-1,-1
1,7,700.5949,432.3939,25.233582,26.458405,0.79736328125,2,-1,-1
1,9,749.7373,429.80667,27.284729,27.143951,0.88671875,2,-1,-1
1,10,748.36597,533.6797,33.060852,38.578064,0.95703125,2,-1,-1
1,11,747.6927,408.01013,16.645325,18.428223,0.58984375,2,-1,-1
1,15,670.2085,370.1975,25.239868,17.603424,0.60498046875,2,-1,-1
1,1,686.5503,615.86633,50.651733,70.39319,0.98828125,2,-1,-1
1,2,622.0461,679.4662,49.190613,82.1012,0.89697265625,2,-1,-1
1,3,536.7928,534.97266,43.30475,60.665894,0.990234375,2,-1,-1
1,5,575.1893,479.54083,39.98523,40.226746,0.94677734375,2,-1,-1
1,6,694.46405,533.4881,37.300476,49.69989,0.9228515625,2,-1,-1
1,7,699.6969,435.26184,25.465027,26.702057,0.72412109375,2,-1,-1
1,9,749.69385,431.7213,27.334717,27.344635,0.8388671875,2,-1,-1
1,10,747.1556,534.81525,35.154114,40.97461,0.90185546875,2,-1,-1
1,11,748.6042,412.22083,15.982178,17.033905,0.57373046875,2,-1,-1
1,15,668.8035,371.73,25.572754,17.878632,0.71484375,2,-1,-1
我是想輸出這種格式，第一列表示幀數，第二列是追蹤出的ID。skip_frames設爲1之後，確實每幀都處理啦，但是幀數卻一直保持不變，正常幀數應該處理一幀加1，這個怎麼改呢，你代碼裏有幀數加1的操作，但是幀數還是一直是1

**Comment by Angel0003** [comment]
> skip_frames指的是跳帧处理，比如2表示每2帧检测一次，如果想每帧处理，设置为1即可，这样就不会跳帧

1,1,690.5098,604.3442,48.11621,66.473816,0.9873046875,2,-1,-1
1,2,624.21564,652.5629,55.833313,94.67615,0.98388671875,2,-1,-1
1,3,543.73895,520.6535,42.325928,60.114014,0.951171875,2,-1,-1
1,5,577.2914,470.5832,38.793823,39.09305,0.591796875,2,-1,-1
1,6,695.8915,525.0203,35.712708,47.11963,0.9453125,2,-1,-1
1,7,699.44855,431.1463,24.614685,25.808441,0.8173828125,2,-1,-1
1,9,748.4025,428.03967,26.481812,26.176147,0.9013671875,2,-1,-1
1,10,746.7273,530.39136,32.677917,38.32538,0.9140625,2,-1,-1
1,11,746.6097,405.83228,16.919495,18.731812,0.58984375,2,-1,-1
1,1,689.91064,610.44495,49.17206,68.15271,0.99072265625,2,-1,-1
1,2,623.7692,664.89124,54.416504,92.378784,0.9794921875,2,-1,-1
1,3,539.9749,528.04517,43.02179,60.783875,0.978515625,2,-1,-1
1,5,576.8351,474.88745,39.076233,39.35431,0.87060546875,2,-1,-1
1,6,695.9689,528.6532,36.289673,48.0719,0.96875,2,-1,-1
1,7,700.5949,432.3939,25.233582,26.458405,0.79736328125,2,-1,-1
1,9,749.7373,429.80667,27.284729,27.143951,0.88671875,2,-1,-1
1,10,748.36597,533.6797,33.060852,38.578064,0.95703125,2,-1,-1
1,11,747.6927,408.01013,16.645325,18.428223,0.58984375,2,-1,-1
1,15,670.2085,370.1975,25.239868,17.603424,0.60498046875,2,-1,-1
1,1,686.5503,615.86633,50.651733,70.39319,0.98828125,2,-1,-1
1,2,622.0461,679.4662,49.190613,82.1012,0.89697265625,2,-1,-1
1,3,536.7928,534.97266,43.30475,60.665894,0.990234375,2,-1,-1
1,5,575.1893,479.54083,39.98523,40.226746,0.94677734375,2,-1,-1
1,6,694.46405,533.4881,37.300476,49.69989,0.9228515625,2,-1,-1
1,7,699.6969,435.26184,25.465027,26.702057,0.72412109375,2,-1,-1
1,9,749.69385,431.7213,27.334717,27.344635,0.8388671875,2,-1,-1
1,10,747.1556,534.81525,35.154114,40.97461,0.90185546875,2,-1,-1
1,11,748.6042,412.22083,15.982178,17.033905,0.57373046875,2,-1,-1
1,15,668.8035,371.73,25.572754,17.878632,0.71484375,2,-1,-1
我是想輸出這種格式，第一列表示幀數，第二列是追蹤出的ID。skip_frames設爲1之後，確實每幀都處理啦，但是幀數卻一直保持不變，正常幀數應該處理一幀加1，這個怎麼改呢，你代碼裏有幀數加1的操作，但是幀數還是一直是1

**Comment by GlassyWing** [comment]
cur_fps 表示的帧数， frames只用作跳帧处理

**Comment by GlassyWing** [comment]
你如果想要每帧都输出帧率，直接用 1 / (cur_time() - prev_time()) 计算出FPS即可

**Comment by GlassyWing** [comment]
cur_fps会在每1s后清零，如果你需要递增处理，最好重新加一个计数变量

**Comment by Angel0003** [comment]
> cur_fps会在每1s后清零，如果你需要递增处理，最好重新加一个计数变量

是的，我重新加了個計數變量
9,1,690.5098,604.3442,48.11621,66.473816,0.9873046875,2,-1,-1
9,2,624.21564,652.5629,55.833313,94.67615,0.98388671875,2,-1,-1
9,3,543.73895,520.6535,42.325928,60.114014,0.951171875,2,-1,-1
9,5,577.2914,470.5832,38.793823,39.09305,0.591796875,2,-1,-1
9,6,695.8915,525.0203,35.712708,47.11963,0.9453125,2,-1,-1
9,7,699.44855,431.1463,24.614685,25.808441,0.8173828125,2,-1,-1
9,9,748.4025,428.03967,26.481812,26.176147,0.9013671875,2,-1,-1
9,10,746.7273,530.39136,32.677917,38.32538,0.9140625,2,-1,-1
9,11,746.6097,405.83228,16.919495,18.731812,0.58984375,2,-1,-1
10,1,689.91064,610.44495,49.17206,68.15271,0.99072265625,2,-1,-1
10,2,623.7692,664.89124,54.416504,92.378784,0.9794921875,2,-1,-1
10,3,539.9749,528.04517,43.02179,60.783875,0.978515625,2,-1,-1
10,5,576.8351,474.88745,39.076233,39.35431,0.87060546875,2,-1,-1
10,6,695.9689,528.6532,36.289673,48.0719,0.96875,2,-1,-1
10,7,700.5949,432.3939,25.233582,26.458405,0.79736328125,2,-1,-1
10,9,749.7373,429.80667,27.284729,27.143951,0.88671875,2,-1,-1
10,10,748.36597,533.6797,33.060852,38.578064,0.95703125,2,-1,-1
10,11,747.6927,408.01013,16.645325,18.428223,0.58984375,2,-1,-1
10,15,670.2085,370.1975,25.239868,17.603424,0.60498046875,2,-1,-1
11,1,686.5503,615.86633,50.651733,70.39319,0.98828125,2,-1,-1
11,2,622.0461,679.4662,49.190613,82.1012,0.89697265625,2,-1,-1
11,3,536.7928,534.97266,43.30475,60.665894,0.990234375,2,-1,-1
11,5,575.1893,479.54083,39.98523,40.226746,0.94677734375,2,-1,-1
11,6,694.46405,533.4881,37.300476,49.69989,0.9228515625,2,-1,-1
11,7,699.6969,435.26184,25.465027,26.702057,0.72412109375,2,-1,-1
11,9,749.69385,431.7213,27.334717,27.344635,0.8388671875,2,-1,-1
11,10,747.1556,534.81525,35.154114,40.97461,0.90185546875,2,-1,-1
11,11,748.6042,412.22083,15.982178,17.033905,0.57373046875,2,-1,-1
11,15,668.8035,371.73,25.572754,17.878632,0.71484375,2,-1,-1
12,1,684.51654,623.94257,51.439636,71.86688,0.955078125,2,-1,-1
12,2,622.0056,694.0283,42.282288,67.24396,0.958984375,2,-1,-1
12,3,530.8172,540.7174,45.54608,63.525818,0.98876953125,2,-1,-1
12,5,572.87964,484.46335,40.207336,40.534515,0.90966796875,2,-1,-1
12,6,693.40204,538.13763,37.02765,49.325195,0.96630859375,2,-1,-1
12,7,698.3294,436.60693,26.236694,27.613861,0.75146484375,2,-1,-1
12,9,749.86255,435.33167,26.881409,27.0784,0.69189453125,2,-1,-1
12,10,746.0344,538.73987,36.59967,42.50653,0.9501953125,2,-1,-1
12,11,747.9254,415.78955,16.304565,16.703552,0.521484375,2,-1,-1
12,15,667.9324,373.2592,25.075806,17.64569,0.78466796875,2,-1,-1
13,1,679.3443,629.80817,52.77527,74.34076,0.99072265625,2,-1,-1
13,2,618.083,709.2924,34.447327,50.86975,0.90771484375,2,-1,-1
13,3,525.2006,548.572,46.451782,64.58142,0.9892578125,2,-1,-1
13,5,568.39734,489.16928,41.706177,42.248444,0.75830078125,2,-1,-1
13,6,691.56885,543.0488,37.783386,50.756897,0.8466796875,2,-1,-1
13,7,697.2926,439.0113,26.245361,27.78952,0.71142578125,2,-1,-1
13,9,749.3983,437.29764,27.01831,27.454773,0.7216796875,2,-1,-1
13,10,745.5781,542.76685,36.501587,42.116455,0.9560546875,2,-1,-1
13,11,746.70447,416.0605,17.712158,17.80188,0.5263671875,2,-1,-1
13,15,665.02057,374.1222,26.383545,18.727264,0.85595703125,2,-1,-1
14,1,674.8577,635.44885,53.811035,76.546265,0.970703125,2,-1,-1
14,2,617.77057,725.9706,26.034119,32.825195,0.751953125,2,-1,-1
14,3,519.8077,555.33374,47.87671,66.24286,0.98974609375,2,-1,-1
14,5,562.7422,492.64444,44.12799,44.65152,0.92431640625,2,-1,-1
14,6,687.9362,547.71643,38.128296,51.274536,0.91845703125,2,-1,-1
14,7,693.404,440.3505,27.302795,28.8302,0.78857421875,2,-1,-1
14,9,745.78217,439.44672,26.699097,27.423798,0.92724609375,2,-1,-1
14,10,741.8026,547.4987,37.04773,42.579956,0.9140625,2,-1,-1
14,11,747.35693,418.33603,17.492004,17.580566,0.5263671875,2,-1,-1
14,15,663.76843,375.07062,26.27533,18.79602,0.92919921875,2,-1,-1
15,1,670.5754,642.9338,55.174866,78.96973,0.9853515625,2,-1,-1
15,2,617.1626,738.43445,21.17511,26.69867,0.751953125,2,-1,-1
15,3,513.4469,563.5811,50.059143,68.4613,0.98779296875,2,-1,-1
15,5,558.48145,498.6748,44.813843,45.56555,0.939453125,2,-1,-1
15,6,684.3317,553.5951,38.432434,51.43573,0.9140625,2,-1,-1
15,7,691.5582,444.52945,26.505371,27.922089,0.70654296875,2,-1,-1
15,9,743.25604,441.00906,27.148804,28.22116,0.8994140625,2,-1,-1
15,10,739.1442,550.5096,37.720642,43.38849,0.9140625,2,-1,-1
15,15,662.75104,375.88187,26.023376,18.815216,0.88134765625,2,-1,-1
15,24,721.39294,343.82938,20.692749,18.646332,0.79833984375,2,-1,-1
16,1,668.32733,648.6792,56.26367,80.5282,0.9853515625,2,-1,-1
16,3,507.9848,570.1423,52.098633,70.891174,0.97802734375,2,-1,-1
16,5,554.30804,502.6976,47.297302,48.616547,0.96142578125,2,-1,-1
16,6,680.94543,557.0111,40.295166,54.393494,0.9814453125,2,-1,-1
16,7,690.1234,446.06924,26.972534,28.372467,0.81396484375,2,-1,-1
16,9,742.82654,444.79297,26.584412,27.701904,0.87158203125,2,-1,-1
16,10,737.69574,552.8631,38.18805,44.003357,0.94970703125,2,-1,-1
16,15,661.0523,376.80737,26.295044,19.146118,0.58984375,2,-1,-1
16,24,720.3967,344.0305,20.713806,18.896301,0.76611328125,2,-1,-1
16,26,691.8336,489.21298,30.281128,39.095978,0.83056640625,2,-1,-1
17,3,500.0988,577.32574,53.548615,72.75989,0.99609375,2,-1,-1
17,5,550.7862,508.1297,47.413025,48.98706,0.951171875,2,-1,-1
17,6,678.46216,559.8243,41.51654,56.776,0.9697265625,2,-1,-1
17,7,687.614,446.74945,28.508545,30.17038,0.763671875,2,-1,-1
17,9,741.8986,446.50003,27.226562,28.472626,0.89306640625,2,-1,-1
爲什麼從第9幀才開始，怎麼不是從第一幀呢，我加的計數變量沒問題吧，我加的變量和cur_fps位置是一樣的，只是if accum_time > 1:那裏cur_fps會置0，我加的變量不置0，這加的沒問題吧，爲啥不從第一針開始追蹤，難道前面幾幀沒檢測出框嗎

**Comment by GlassyWing** [comment]
这是deepsort的检测规则，它会在多次命中的情况下才确定跟踪，你可以把deesort参数中的n_init设为0，这样相当于检测到就跟踪

**Comment by Angel0003** [comment]
> 这是deepsort的检测规则，它会在多次命中的情况下才确定跟踪，你可以把deesort参数中的n_init设为0，这样相当于检测到就跟踪

這個值設置成多少合適呢，我改成0跑出來的視頻看上去感覺效果也不錯。還有追蹤出來的每個框的速度和加速度知道咋算不大佬，這個是不是卡爾曼濾波那裏，具體哪個量表示速度和加速度呢，均值和方差代表誰的均值和方差？

**Comment by GlassyWing** [comment]
这个值一般遮挡发生次数越多，设置越大越好，当然，前期将会有较大可能还没跟踪到目标，目标就消失了，因此其大小需要手动测试调整。至于卡尔曼滤波器，它并非计算速度和加速度，我不做多余解释，你可以网上搜索更详解的解释。另外由于这里的卡尔曼滤波器代码加入了批量维，所以阅读起来较为困难，你可以参考原版实现https://github.com/nwojke/deep_sort

**Comment by Angel0003** [comment]
> 这个值一般遮挡发生次数越多，设置越大越好，当然，前期将会有较大可能还没跟踪到目标，目标就消失了，因此其大小需要手动测试调整。至于卡尔曼滤波器，它并非计算速度和加速度，我不做多余解释，你可以网上搜索更详解的解释。另外由于这里的卡尔曼滤波器代码加入了批量维，所以阅读起来较为困难，你可以参考原版实现https://github.com/nwojke/deep_sort

好的，非常感谢大佬！卡尔曼滤波的状态变量里是不是有速度和加速度？有没有办法直接输出来这两个量呢，看到知乎上有人说，均值里面有速度，不过我没看懂

**Comment by GlassyWing** [comment]
> > 这个值一般遮挡发生次数越多，设置越大越好，当然，前期将会有较大可能还没跟踪到目标，目标就消失了，因此其大小需要手动测试调整。至于卡尔曼滤波器，它并非计算速度和加速度，我不做多余解释，你可以网上搜索更详解的解释。另外由于这里的卡尔曼滤波器代码加入了批量维，所以阅读起来较为困难，你可以参考原版实现https://github.com/nwojke/deep_sort
> 
> 好的，非常感谢大佬！卡尔曼滤波的状态变量里是不是有速度和加速度？有没有办法直接输出来这两个量呢，看到知乎上有人说，均值里面有速度，不过我没看懂

均值向量是一个8维向量，前4维表示x,y,a,h, 后4维分别是前4维的速度，不包含加速度
