### ISSUE TITLE
请问我想用Ground Truth单独测试追踪的评价指标应该怎么做

### ISSUE THREAD

**Issue by Angel0003** [GlassyWing/yolo_deepsort#4]
请问大佬，我想用Ground Truth单独测试追踪的评价指标应该怎么做，就是我想用groundtruth作为追踪输入，得到追踪的结果，不用yolo跑出来的检测结果作为追踪的输入，该怎么做？我的ground truth是下面的格式
1,0,824,771,127,129,1,4,0,0
2,0,828,761,124,123,1,4,0,0
3,0,833,752,120,116,1,4,0,0
4,0,834,741,119,117,1,4,0,0
5,0,836,731,117,117,1,4,0,0
6,0,840,720,114,113,1,4,0,0
7,0,844,710,111,108,1,4,0,0
8,0,848,700,109,104,1,4,0,0
9,0,850,692,107,102,1,4,0,0
10,0,852,685,105,100,1,4,0,0
11,0,855,678,102,98,1,4,0,0
12,0,857,671,100,95,1,4,0,0
13,0,859,664,98,93,1,4,0,0
14,0,862,656,95,92,1,4,0,0
15,0,864,649,93,90,1,4,0,0
16,0,866,642,91,87,1,4,0,0
17,0,869,635,88,85,1,4,0,0
18,0,871,628,86,83,1,4,0,0
19,0,874,621,84,81,1,4,0,0
20,0,875,615,83,79,1,4,0,0
21,0,877,610,81,77,1,4,0,0
22,0,878,604,80,76,1,4,0,0
23,0,880,599,79,74,1,4,0,0

**Comment by GlassyWing** [comment]
跟踪器的输入只是一批检测框，你可以在此处打印查看输入格式：https://github.com/GlassyWing/yolo_deepsort/blob/9377845a9fc089c3efe9b2a143c556f824375ac0/yolo3/detect/video_detect.py#L147

**Comment by Angel0003** [comment]
> 跟踪器的输入只是一批检测框，你可以在此处打印查看输入格式：
> 
> https://github.com/GlassyWing/yolo_deepsort/blob/9377845a9fc089c3efe9b2a143c556f824375ac0/yolo3/detect/video_detect.py#L147
我就是这么做的，我的Ground truth是一个个的txt文件，他是一些视频的标签，一个视频对应一个txt文件，每个txt文件里的内容都是上面的格式。但是我怎么把txt文件送入追踪器里（格式我能调整成一样），而不经过yolo检测，需要把yolo部分屏蔽掉，直接输入txt文件，该怎么改？

**Comment by GlassyWing** [comment]
> > 跟踪器的输入只是一批检测框，你可以在此处打印查看输入格式：
> > https://github.com/GlassyWing/yolo_deepsort/blob/9377845a9fc089c3efe9b2a143c556f824375ac0/yolo3/detect/video_detect.py#L147
> > 
> > 我就是这么做的，我的Ground truth是一个个的txt文件，他是一些视频的标签，一个视频对应一个txt文件，每个txt文件里的内容都是上面的格式。但是我怎么把txt文件送入追踪器里（格式我能调整成一样），而不经过yolo检测，需要把yolo部分屏蔽掉，直接输入txt文件，该怎么改？

把图像检测器替换为你自己的模块就行，即输入txt，输出检测框
https://github.com/GlassyWing/yolo_deepsort/blob/9377845a9fc089c3efe9b2a143c556f824375ac0/yolo3/detect/video_detect.py#L133

**Comment by Angel0003** [comment]
> > > 跟踪器的输入只是一批检测框，你可以在此处打印查看输入格式：
> > > https://github.com/GlassyWing/yolo_deepsort/blob/9377845a9fc089c3efe9b2a143c556f824375ac0/yolo3/detect/video_detect.py#L147
> > > 
> > > 我就是这么做的，我的Ground truth是一个个的txt文件，他是一些视频的标签，一个视频对应一个txt文件，每个txt文件里的内容都是上面的格式。但是我怎么把txt文件送入追踪器里（格式我能调整成一样），而不经过yolo检测，需要把yolo部分屏蔽掉，直接输入txt文件，该怎么改？
> 
> 把图像检测器替换为你自己的模块就行，即输入txt，输出检测框
> 
> https://github.com/GlassyWing/yolo_deepsort/blob/9377845a9fc089c3efe9b2a143c556f824375ac0/yolo3/detect/video_detect.py#L133
能详细说下怎么改吗大佬，还是运行那个video_deepsort.py吗?在这里输入的话，那不是要经过yolo检测啦，我现在已有的GT相当于已经有检测好的框了，只需要把这些框追踪出来，输入txt，得到追踪结果，我只需要看我现在已有的框单纯的追踪的各项指标。可以加个qq沟通吗2609875305

**Comment by GlassyWing** [comment]
> 2609875305

already added
