### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by fdcqqqq** [GlassyWing/yolo_deepsort#6]
你好,我在用您代码的时候检测不到是怎么回事?检测框不显示直接,希望您看到后回复我一下,谢谢

**Comment by GlassyWing** [comment]
> 你好,我在用您代码的时候检测不到是怎么回事?检测框不显示直接,希望您看到后回复我一下,谢谢

请提供运行脚本，和错误日志（如果有的话）

**Comment by GlassyWing** [comment]
> 你好,我在用您代码的时候检测不到是怎么回事?检测框不显示直接,希望您看到后回复我一下,谢谢

默认使用了追踪掩码，只追踪人或汽车，如果要追踪其它类，将class_mask参数移除即可

**Comment by fdcqqqq** [comment]
我的视频里有车有人就是检测不到

**Comment by GlassyWing** [comment]
> 我的视频里有车有人就是检测不到

使用的是否是官方得weights与config，还是自训练的？将thres值减小再测试

**Comment by fdcqqqq** [comment]
[使用的官方的,thres调小之后确实有的显示了,但是还是不行,视频的车和人都检测不到,我把class_mask参数去掉后,他大部分的只检测到了traffic light

**Comment by GlassyWing** [comment]
> [使用的官方的,thres调小之后确实有的显示了,但是还是不行,视频的车和人都检测不到,我把class_mask参数去掉后,他大部分的只检测到了traffic light

是所有视频都这样，还是只是某个视频如此，建议使用不同视频测试一下

**Comment by fdcqqqq** [comment]
所有视频车和人都检测不到,是不是MP4格式问题
代码就这样的:video_detector = VideoDetector(model, "config/coco.names",
                                   # font_path="font/Noto_Serif_SC/NotoSerifSC-Regular.otf",
                                   # font_size=14,
                                   thickness=2,
                                   skip_frames=2,
                                   thres=0.05,
                                   # class_mask=[0, 2, 4],
                                   nms_thres=0.4,
                                   tracker=tracker,
                                   half=True)

    for image, detections, _ in video_detector.detect("./test.mp4",
                                                      # output_path="../data/output.ts",
                                                      real_show=True,
                                                      skip_secs=0):

**Comment by GlassyWing** [comment]
> 所有视频车和人都检测不到,是不是MP4格式问题
> 代码就这样的:video_detector = VideoDetector(model, "config/coco.names",
> # font_path="font/Noto_Serif_SC/NotoSerifSC-Regular.otf",
> # font_size=14,
> thickness=2,
> skip_frames=2,
> thres=0.05,
> # class_mask=[0, 2, 4],
> nms_thres=0.4,
> tracker=tracker,
> half=True)
> 
> ```
> for image, detections, _ in video_detector.detect("./test.mp4",
>                                                   # output_path="../data/output.ts",
>                                                   real_show=True,
>                                                   skip_secs=0):
> ```

将 tracker=tracker 注释，再观测一下

**Comment by fdcqqqq** [comment]
显示没什么区别只是速度变快了

**Comment by GlassyWing** [comment]
> 显示没什么区别只是速度变快了

em...，可以尝试下载flv格式的视频进行测试

**Comment by fdcqqqq** [comment]
啊,我去找个试试看,谢谢啦,麻烦

**Comment by GlassyWing** [comment]
> 啊,我去找个试试看,谢谢啦,麻烦

理论上视频格式没有特别要求，只是确认一下其它包含人或汽车的视频是否仍然具有相同问题，另外可以把half参数设为False

**Comment by Angel0003** [comment]
我能检测人，car，truck之类的，但是检测不到bus，请问这是为什么？

**Comment by GlassyWing** [comment]
> 我能检测人，car，truck之类的，但是检测不到bus，请问这是为什么？

可以截图展示一下吗
