### ISSUE TITLE
替换Reid模型

### ISSUE THREAD

**Issue by Angel0003** [GlassyWing/yolo_deepsort#7]
你好，请教下大佬，我想改进deepsort中reid模型，原论文是在market1501上训练的模型，对人的重识别效果好，对车的可能不好，所以我想在车的数据上训练出个模型，请问reid部分你和原论文做了哪些改动，还是保持没变，我该怎么训练？

**Comment by GlassyWing** [comment]
deep 部分采用模型使用该仓库中的模型https://github.com/ZQPei/deep_sort_pytorch, 训练方法请参考该仓库readme

**Comment by Angel0003** [comment]
> 你好，请教下大佬，我想改进deepsort中reid模型，原论文是在market1501上训练的模型，对人的重识别效果好，对车的可能不好，所以我想在车的数据上训练出个模型，请问reid部分你和原论文做了哪些改动，还是保持没变，我该怎么训练？

我想更改reid部分换成更强的reid模型该怎么做，如果模型保存的是.t7格式的模型我就可以直接拿来用吗，可以qq交流吗，我在qq上给你发消息了，抽空看下呗。

**Comment by GlassyWing** [comment]
The problem has been dealt with elsewhere
